### PR TITLE
add fonts again

### PR DESCRIPTION
**Pull request by m4rc1e**

### CODE REVIEW

**Comment by Typedesigners** [comment]
Thank you very much! Can I publish a new release of Anta now?

**Comment by m4rc1e** [comment]
I think we're alright. I just readded the fonts dir. I'll submit to Google Fonts now.

**Comment by Typedesigners** [comment]
Thank you very much!

**Comment by Typedesigners** [comment]
Hello, Is the release completed, when can Anta be downloaded from Google Fonts?

**Comment by m4rc1e** [comment]
May take a few weeks. I'll keep you posted.

**Comment by Typedesigners** [comment]
Hello, a year ago today I submitted Anta for Google Fonts. A year has passed since then.  It would be nice if the font family were now published on Google Fonts.

**Comment by m4rc1e** [comment]
Read my last comment.

**Comment by Typedesigners** [comment]
Thank you.

**Pull request merged**
